version: '3.2'
services:
  kibana:
    image: kibana:7.6.1
    environment:
      SERVER_NAME: kibana
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch:7.6.1
    environment:
      - cluster.name=elasticsearch
      - node.name=es
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
    volumes:
      - ./elasticsearch/data:/elasticsearch/data
    ports:
      - 9200:9200
